config/routes.rb
Rails3demo::Application.routes.draw do
  resources :watchings
  resources :episodes

end

app/models/episode.rb
class Episode < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  respond_to :html, :xml, :json

  def index
    @episodes = Episode.all
    respond_with Episode.all
  end

  def show
    @episode = Episode.find(params[:id])
    respond_with @episode
  end

  def new
    @episode = Episode.new
    respond_with @episode
  end

  def edit
    @episode = Episode.find(params[:id])
  end

  def create
    @episode = Episode.new(params[:episode])
    flash[:notice] = 'Episode was successfully created.' if @episode.save

    respond_with @episode
  end

  def update
    @episode = Episode.find(params[:id])
    flash[:notice] = 'Episode was successfully updated.' if @episode.save
    respond_with @episode
  end

  def destroy
    @episode = Episode.find(params[:id])
    @episode.destroy

    respond_with @episode
  end
end

app/controllers/watchings_controller.rb
class WatchingsController < ApplicationController
  def index
    # build query of all episodes ordered by season and sequence columns
    @episodes = Episode.order(:season, :sequence)

    # build query of all episodes where viewd_at is NULL ordered by season and sequence columns
    @unwatched = @episodes.where(:viewed_at=>nil)
    
    # executes both queries to build result arrays
    @watched = @episodes - @unwatched
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/watchings_helper.rb
module WatchingsHelper
end

app/views/episodes/_form.html.erb
<%= form_for(@episode) do |f| %>
  <% if @episode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@episode.errors.count, "error") %> prohibited this episode from being saved:</h2>

      <ul>
      <% @episode.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :season %><br />
    <%= f.text_field :season %>
  </div>
  <div class="field">
    <%= f.label :sequence %><br />
    <%= f.text_field :sequence %>
  </div>
  <div class="field">
    <%= f.label :viewed_at %><br />
    <%= f.datetime_select :viewed_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/episodes/edit.html.erb
<h1>Editing episode</h1>

<%= render 'form' %>

<%= link_to 'Show', @episode %> |
<%= link_to 'Back', episodes_path %>

app/views/episodes/index.html.erb
<h1>Listing episodes</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Season</th>
    <th>Sequence</th>
    <th>Viewed at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @episodes.each do |episode| %>
  <tr>
    <td><%= episode.name %></td>
    <td><%= episode.season %></td>
    <td><%= episode.sequence %></td>
    <td><%= episode.viewed_at %></td>
    <td><%= link_to 'Show', episode %></td>
    <td><%= link_to 'Edit', edit_episode_path(episode) %></td>
    <td><%= link_to 'Destroy', episode, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Episode', new_episode_path %>

app/views/episodes/new.html.erb
<h1>New episode</h1>

<%= render 'form' %>

<%= link_to 'Back', episodes_path %>

app/views/episodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @episode.name %>
</p>

<p>
  <b>Season:</b>
  <%= @episode.season %>
</p>

<p>
  <b>Sequence:</b>
  <%= @episode.sequence %>
</p>

<p>
  <b>Viewed at:</b>
  <%= @episode.viewed_at %>
</p>


<%= link_to 'Edit', edit_episode_path(@episode) %> |
<%= link_to 'Back', episodes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails3demo</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/watchings/_episode_list.html.erb
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Season and Episode number</th>
    </tr>
  </thead>
  <tbody>
    <%= render :partial=>'episode_list_entry', :collection=>episode_list %>
  </tbody>
</table>

app/views/watchings/_episode_list_entry.html.erb
<tr>
  <td><%= episode_list_entry.name %></td>
  <td><%= episode_list_entry.season %> / <%= episode_list_entry.sequence %></td>
</tr>

app/views/watchings/index.html.erb
<h1>Episodes</h1>

<h2>Unwatched</h2>
<%= render :partial=>'episode_list', :locals=>{:episode_list=>@unwatched} %>

<h2>Watched</h2>
<%= render :partial=>'episode_list', :locals=>{:episode_list=>@watched} %>